version: 2.1

# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7

jobs:
  build:
    docker:
      - image: cimg/node:16.10.0
    steps:
      - checkout
      - run: node --version
  test:
    docker:
      - image: cimg/node:16.10.0
    steps:
      - run: npm run test

  es-lint:
    docker:
      - image: cimg/node:16.10.0
    steps:
      - run: npm run lint

# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  version: 2
  quality-control:
    jobs:
      - test:
          filters:
            branches:
              only:
                - staging
                - master
      - es-lint:
          filters:
            branches:
              only:
                - staging
                - master
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - staging
                - master
