version: 2.1

# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7

jobs:
  run_tests:
    docker:
      - image: cimg/node:16.10.0
    working_directory: ~/project
    steps:
      - checkout
      - run: node --version
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run:
          name: Run Unit Tests
          command: npm run test:cov
      - store_test_results:
          path: coverage
      - store_artifacts:
          path: coverage
          destination: /tmp/artifacts/coverage
  run_lint:
    docker:
      - image: cimg/node:16.10.0
    working_directory: ~/project
    steps:
      - checkout
      - run: node --version
      - run: npm run lint
  build:
    docker:
      - image: cimg/node:16.10.0
    working_directory: ~/project
    steps:
      - run: node --version
      - run:
          name: Build application
          command: npm run build
      - store_artifacts:
          path: dist
          destination: /tmp/artifacts/builds

# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  version: 2
  test-and-build:
    jobs:
      - run_tests:
          filters:
            branches:
              only:
                - staging
                - master
      - run_lint:
          filters:
            branches:
              only:
                - staging
                - master
      - build:
          requires:
            - run_tests
            - run_lint
          filters:
            branches:
              only:
                - staging
                - master
